version: '3'
services:

  #PHP Service
  test-php:
    build: ./
    image: test/php
    container_name: test-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/default
    volumes:
      - ./:/var/www/default
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - test-app-network

  #Postgresql Service
  test-db:
    image: postgres:14.1
    container_name: test-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: '12345'
      POSTGRES_DB: 'test_php'
      POSTGRES_USER: 'php_user'
      POSTGRES_PASSWORD: '12345'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - test-app-network


  #Nginx Service
  test-webserver:
    image: nginx:alpine
    container_name: test-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/default
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - test-app-network
    depends_on:
      - test-php
      - test-db


#Docker Networks
networks:
  test-app-network:
    driver: bridge

#Volumes
volumes:
  pgdata:
    driver: local
